name: telegram-notify-action
description: 'Send a Telegram message when a github event is triggered'
author: 'georgepstaylor'
inputs:
    telegram_bot_token:
        description: 'Telegram bot token'
        required: true
    telegram_chat_id:
        description: 'Telegram chat id'
        required: true
    telegram_msg_text:
        description: 'Telegram message text'
        required: true
    telegram_parse_mode:
        description: 'Telegram parse mode'
        required: false
        default: 'Markdown'
    telegram_inline_keyboard:
        description: 'Telegram inline keyboard'
        required: false
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
    icon: 'alert-circle'
    color: 'green'